# Generated by Django 3.1.5 on 2026-04-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_auto_20260407_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PRESENT', 'PRESENT')], default='PRESENT', max_length=50),
        ),
    ]
